hwdec=v4l2m2m-copy
hwdec-codecs=hevc,vp9
vo=gpu
gpu-context=drm
video-sync=display-resample
display-fps=60
scale=bilinear
cscale=bilinear
dither-depth=no
vd-lavc-threads=4
input-ipc-server=/tmp/mpv.sock
osd-duration=3000
fs
